/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import operations.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.text.BadLocationException;

/**
 *
 * @author berik
 */
public class BasicCalculator extends javax.swing.JFrame {

    private int decimalCounter = 8;
    private String showNumber = "0";
    private String txAHistoryStr = "";
    private OperationType operation = OperationType.NONE;
    private OperationType subOperation = OperationType.NONE;
    private double operateOne;
    private double operateTwo = Double.MAX_VALUE;
    private double result;

    /**
     * Creates new form BasicCalculator
     */
    public BasicCalculator() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(64, 40, 89));

        precisionDecimalsGroup.add(jRadioButtonNoDecimals);
        precisionDecimalsGroup.add(jRadioButtonOneDecimal);
        precisionDecimalsGroup.add(jRadioButtonTwoDecimals);
        precisionDecimalsGroup.add(jRadioButtonThreeDecimals);
        precisionDecimalsGroup.add(jRadioButtonFourDecimals);
        precisionDecimalsGroup.add(jRadioButtonFiveDecimals);
        precisionDecimalsGroup.add(jRadioButtonSixDecimals);
        precisionDecimalsGroup.add(jRadioButtonSevenDecimals);
        precisionDecimalsGroup.add(jRadioButtonEightDecimals);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        precisionDecimalsGroup = new javax.swing.ButtonGroup();
        aboutDialog = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonTwo = new javax.swing.JButton();
        jButtonOne = new javax.swing.JButton();
        jButtonComma = new javax.swing.JButton();
        jButtonZero = new javax.swing.JButton();
        jButtonSix = new javax.swing.JButton();
        jButtonFour = new javax.swing.JButton();
        jButtonFive = new javax.swing.JButton();
        jButtonNine = new javax.swing.JButton();
        jButtonSeven = new javax.swing.JButton();
        jButtonEight = new javax.swing.JButton();
        jButtonTrhee = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonDivide = new javax.swing.JButton();
        jButtonMultiply = new javax.swing.JButton();
        jButtonLess = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButtonEquals = new javax.swing.JButton();
        jButtonClearEnd = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        TxfLive = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxAHistory = new javax.swing.JTextArea();
        TxfScreen = new javax.swing.JTextField();
        jButtonCloseBracket = new javax.swing.JButton();
        jButtonOpenBracket = new javax.swing.JButton();
        jButtonClearHistory = new javax.swing.JButton();
        jToggleLiveMode = new javax.swing.JToggleButton();
        jButtonChangeSign = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonNoDecimals = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonOneDecimal = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonTwoDecimals = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonThreeDecimals = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonFourDecimals = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonFiveDecimals = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonSixDecimals = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonSevenDecimals = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonEightDecimals = new javax.swing.JRadioButtonMenuItem();

        aboutDialog.setTitle("Acerca de");
        aboutDialog.setAlwaysOnTop(true);
        aboutDialog.setBackground(new java.awt.Color(204, 204, 255));
        aboutDialog.setResizable(false);
        aboutDialog.setLocationRelativeTo(null);
        aboutDialog.setSize(new java.awt.Dimension(419, 423));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/util/about.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 68, 138));
        jLabel2.setText("Calculadora Java 1.0");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(106, 68, 138));
        jTextArea1.setRows(3);
        jTextArea1.setText("Diseñada por José Anotnio Yáñez Jiménez\nDesarrollo de Aplicaciones Web, IES Galileo\nMarzo de 2013");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(204, 204, 255));
        jTextArea1.setDragEnabled(false);
        jTextArea1.setFocusTraversalKeysEnabled(false);
        jTextArea1.setFocusable(false);
        jScrollPane2.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 385, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(77, 77, 77)
                        .add(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jLabel2)
                .add(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(51, 51, 51))
        );

        org.jdesktop.layout.GroupLayout aboutDialogLayout = new org.jdesktop.layout.GroupLayout(aboutDialog.getContentPane());
        aboutDialog.getContentPane().setLayout(aboutDialogLayout);
        aboutDialogLayout.setHorizontalGroup(
            aboutDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        aboutDialogLayout.setVerticalGroup(
            aboutDialogLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(64, 40, 89));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(153, 51, 255));
        setResizable(false);

        jButtonTwo.setBackground(new java.awt.Color(108, 81, 136));
        jButtonTwo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonTwo.setForeground(new java.awt.Color(204, 204, 255));
        jButtonTwo.setText("2");
        jButtonTwo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberClick(evt);
            }
        });

        jButtonOne.setBackground(new java.awt.Color(108, 81, 136));
        jButtonOne.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonOne.setForeground(new java.awt.Color(204, 204, 255));
        jButtonOne.setText("1");
        jButtonOne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberClick(evt);
            }
        });

        jButtonComma.setBackground(new java.awt.Color(204, 204, 255));
        jButtonComma.setForeground(new java.awt.Color(90, 48, 115));
        jButtonComma.setText(",");
        jButtonComma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonComma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCommaActionPerformed(evt);
            }
        });

        jButtonZero.setBackground(new java.awt.Color(108, 81, 136));
        jButtonZero.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonZero.setForeground(new java.awt.Color(204, 204, 255));
        jButtonZero.setText("0");
        jButtonZero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberClick(evt);
            }
        });

        jButtonSix.setBackground(new java.awt.Color(108, 81, 136));
        jButtonSix.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonSix.setForeground(new java.awt.Color(204, 204, 255));
        jButtonSix.setText("6");
        jButtonSix.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberClick(evt);
            }
        });

        jButtonFour.setBackground(new java.awt.Color(108, 81, 136));
        jButtonFour.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonFour.setForeground(new java.awt.Color(204, 204, 255));
        jButtonFour.setText("4");
        jButtonFour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberClick(evt);
            }
        });

        jButtonFive.setBackground(new java.awt.Color(108, 81, 136));
        jButtonFive.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonFive.setForeground(new java.awt.Color(204, 204, 255));
        jButtonFive.setText("5");
        jButtonFive.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberClick(evt);
            }
        });

        jButtonNine.setBackground(new java.awt.Color(108, 81, 136));
        jButtonNine.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonNine.setForeground(new java.awt.Color(204, 204, 255));
        jButtonNine.setText("9");
        jButtonNine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberClick(evt);
            }
        });

        jButtonSeven.setBackground(new java.awt.Color(108, 81, 136));
        jButtonSeven.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonSeven.setForeground(new java.awt.Color(204, 204, 255));
        jButtonSeven.setText("7");
        jButtonSeven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberClick(evt);
            }
        });

        jButtonEight.setBackground(new java.awt.Color(108, 81, 136));
        jButtonEight.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonEight.setForeground(new java.awt.Color(204, 204, 255));
        jButtonEight.setText("8");
        jButtonEight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberClick(evt);
            }
        });

        jButtonTrhee.setBackground(new java.awt.Color(108, 81, 136));
        jButtonTrhee.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonTrhee.setForeground(new java.awt.Color(204, 204, 255));
        jButtonTrhee.setText("3");
        jButtonTrhee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTrhee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberClick(evt);
            }
        });

        jButtonPlus.setBackground(new java.awt.Color(204, 204, 255));
        jButtonPlus.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButtonPlus.setForeground(new java.awt.Color(90, 48, 115));
        jButtonPlus.setText("+");
        jButtonPlus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestOperation(evt);
            }
        });

        jButtonDivide.setBackground(new java.awt.Color(204, 204, 255));
        jButtonDivide.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButtonDivide.setForeground(new java.awt.Color(90, 48, 115));
        jButtonDivide.setText("/");
        jButtonDivide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestOperation(evt);
            }
        });

        jButtonMultiply.setBackground(new java.awt.Color(204, 204, 255));
        jButtonMultiply.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButtonMultiply.setForeground(new java.awt.Color(90, 48, 115));
        jButtonMultiply.setText("*");
        jButtonMultiply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestOperation(evt);
            }
        });

        jButtonLess.setBackground(new java.awt.Color(204, 204, 255));
        jButtonLess.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButtonLess.setForeground(new java.awt.Color(90, 48, 115));
        jButtonLess.setText("-");
        jButtonLess.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestOperation(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(204, 204, 255));
        jButton17.setForeground(new java.awt.Color(90, 48, 115));
        jButton17.setText("1/x");
        jButton17.setToolTipText("Recíproco");
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reciproc(evt);
            }
        });

        jButtonEquals.setBackground(new java.awt.Color(204, 204, 255));
        jButtonEquals.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButtonEquals.setForeground(new java.awt.Color(90, 48, 115));
        jButtonEquals.setText("=");
        jButtonEquals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualsActionPerformed(evt);
            }
        });

        jButtonClearEnd.setBackground(new java.awt.Color(204, 204, 255));
        jButtonClearEnd.setForeground(new java.awt.Color(90, 48, 115));
        jButtonClearEnd.setText("CE");
        jButtonClearEnd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClearEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearEndActionPerformed(evt);
            }
        });

        jButtonBack.setBackground(new java.awt.Color(204, 204, 255));
        jButtonBack.setForeground(new java.awt.Color(90, 48, 115));
        jButtonBack.setText("←");
        jButtonBack.setToolTipText("");
        jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonClear.setBackground(new java.awt.Color(204, 204, 255));
        jButtonClear.setForeground(new java.awt.Color(90, 48, 115));
        jButtonClear.setText("C");
        jButtonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        TxfLive.setEditable(false);
        TxfLive.setBackground(new java.awt.Color(108, 81, 136));
        TxfLive.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        TxfLive.setForeground(new java.awt.Color(204, 204, 255));
        TxfLive.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxfLive.setDisabledTextColor(new java.awt.Color(102, 0, 153));
        TxfLive.setFocusTraversalKeysEnabled(false);
        TxfLive.setFocusable(false);
        TxfLive.setSelectionColor(new java.awt.Color(102, 0, 153));

        TxAHistory.setEditable(false);
        TxAHistory.setBackground(new java.awt.Color(108, 81, 136));
        TxAHistory.setColumns(20);
        TxAHistory.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        TxAHistory.setForeground(new java.awt.Color(204, 204, 255));
        TxAHistory.setRows(4);
        TxAHistory.setToolTipText("Historial de operaciones");
        TxAHistory.setFocusTraversalKeysEnabled(false);
        TxAHistory.setFocusable(false);
        jScrollPane1.setViewportView(TxAHistory);

        TxfScreen.setEditable(false);
        TxfScreen.setBackground(new java.awt.Color(204, 204, 255));
        TxfScreen.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        TxfScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxfScreen.setText("0");
        TxfScreen.setFocusTraversalKeysEnabled(false);
        TxfScreen.setFocusable(false);

        jButtonCloseBracket.setText(")");
        jButtonCloseBracket.setToolTipText("");
        jButtonCloseBracket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCloseBracket.setEnabled(false);
        jButtonCloseBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseBracketActionPerformed(evt);
            }
        });

        jButtonOpenBracket.setText("(");
        jButtonOpenBracket.setToolTipText("");
        jButtonOpenBracket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonOpenBracket.setEnabled(false);
        jButtonOpenBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenBracketActionPerformed(evt);
            }
        });

        jButtonClearHistory.setBackground(new java.awt.Color(108, 81, 136));
        jButtonClearHistory.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButtonClearHistory.setForeground(new java.awt.Color(204, 204, 255));
        jButtonClearHistory.setText("C");
        jButtonClearHistory.setToolTipText("Borrar historial");
        jButtonClearHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClearHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearHistoryActionPerformed(evt);
            }
        });

        jToggleLiveMode.setBackground(new java.awt.Color(204, 204, 255));
        jToggleLiveMode.setForeground(new java.awt.Color(90, 48, 115));
        jToggleLiveMode.setText("Cálculo combinado");
        jToggleLiveMode.setToolTipText("El cálculo combinado espera a que se presione el botón de resultado para evaluar una operación compleja combinando varias operaciones simples");
        jToggleLiveMode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleLiveMode.setEnabled(false);
        jToggleLiveMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleLiveModeActionPerformed(evt);
            }
        });

        jButtonChangeSign.setBackground(new java.awt.Color(204, 204, 255));
        jButtonChangeSign.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonChangeSign.setForeground(new java.awt.Color(90, 48, 115));
        jButtonChangeSign.setText("+/-");
        jButtonChangeSign.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonChangeSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeSignActionPerformed(evt);
            }
        });

        jMenuBar1.setForeground(new java.awt.Color(88, 65, 115));

        jMenu1.setForeground(new java.awt.Color(88, 65, 115));
        jMenu1.setText("Calculadora");

        jMenuItem1.setText("Acerca de");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAboutDialog(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(88, 65, 115));
        jMenu2.setText("Precisión");

        jRadioButtonNoDecimals.setText("Sin decimales");
        jRadioButtonNoDecimals.setActionCommand("0");
        jRadioButtonNoDecimals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDecimalPrecision(evt);
            }
        });
        jMenu2.add(jRadioButtonNoDecimals);

        jRadioButtonOneDecimal.setText("1 decimal");
        jRadioButtonOneDecimal.setActionCommand("1");
        jRadioButtonOneDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDecimalPrecision(evt);
            }
        });
        jMenu2.add(jRadioButtonOneDecimal);

        jRadioButtonTwoDecimals.setText("2 decimales");
        jRadioButtonTwoDecimals.setActionCommand("2");
        jRadioButtonTwoDecimals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDecimalPrecision(evt);
            }
        });
        jMenu2.add(jRadioButtonTwoDecimals);

        jRadioButtonThreeDecimals.setText("3 decimales");
        jRadioButtonThreeDecimals.setActionCommand("3");
        jRadioButtonThreeDecimals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDecimalPrecision(evt);
            }
        });
        jMenu2.add(jRadioButtonThreeDecimals);

        jRadioButtonFourDecimals.setText("4 decimales");
        jRadioButtonFourDecimals.setActionCommand("4");
        jMenu2.add(jRadioButtonFourDecimals);

        jRadioButtonFiveDecimals.setText("5 decimales");
        jRadioButtonFiveDecimals.setActionCommand("5");
        jMenu2.add(jRadioButtonFiveDecimals);

        jRadioButtonSixDecimals.setText("6 decimales");
        jRadioButtonSixDecimals.setActionCommand("6");
        jMenu2.add(jRadioButtonSixDecimals);

        jRadioButtonSevenDecimals.setText("7 decimales");
        jRadioButtonSevenDecimals.setActionCommand("7");
        jMenu2.add(jRadioButtonSevenDecimals);

        jRadioButtonEightDecimals.setSelected(true);
        jRadioButtonEightDecimals.setText("8 decimales");
        jRadioButtonEightDecimals.setActionCommand("8");
        jRadioButtonEightDecimals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDecimalPrecision(evt);
            }
        });
        jMenu2.add(jRadioButtonEightDecimals);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(jScrollPane1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonClearHistory, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(TxfScreen)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(jToggleLiveMode, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(12, 12, 12))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                        .add(0, 0, Short.MAX_VALUE)
                                        .add(jButtonChangeSign, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)))
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(jButtonBack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jButtonClearEnd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jButtonClear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(layout.createSequentialGroup()
                                                .add(jButtonFour, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                .add(jButtonFive, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                .add(jButtonSix, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                                .add(org.jdesktop.layout.GroupLayout.LEADING, jButtonZero, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                                    .add(jButtonOne, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                    .add(jButtonTwo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(12, 12, 12)
                                                    .add(jButtonTrhee, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                        .add(18, 18, 18)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(layout.createSequentialGroup()
                                                .add(jButtonPlus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                .add(jButtonLess, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(layout.createSequentialGroup()
                                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jButtonComma, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                    .add(jButton17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                .add(jButtonEquals, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, TxfLive)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .add(jButtonOpenBracket, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButtonCloseBracket, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButtonSeven, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButtonEight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButtonNine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jButtonMultiply, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButtonDivide, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonClearHistory, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(TxfLive, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(TxfScreen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 46, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButtonClearEnd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonClear, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonBack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(12, 12, 12))
                    .add(layout.createSequentialGroup()
                        .add(jToggleLiveMode, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jButtonMultiply, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonDivide, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jButtonSeven, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonEight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonNine, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonCloseBracket, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButtonOpenBracket, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButtonPlus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonLess, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(jButton17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jButtonComma, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jButtonEquals, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButtonFour, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonFive, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonSix, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButtonOne, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonTwo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonTrhee, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jButtonZero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonChangeSign, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .add(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numberClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberClick
        // TODO add your handling code here:
        if(txAHistoryStr.equals(""))
        {showNumber="";}
        if (!operation.equals(OperationType.BRACKETS) && !subOperation.equals(OperationType.RECIPROC)) {
            if (TxfScreen.getText().equals("0") && evt.getActionCommand().equals("0")) {
                showNumber = "0";
            } else if (TxfScreen.getText().equals("0") && !evt.getActionCommand().equals("0")) {
                if (showNumber.equals("0")) {
                    showNumber = "";
                }
                showNumber = showNumber + evt.getActionCommand();
                txAHistoryStr = txAHistoryStr + (evt.getActionCommand());
                TxfLive.setText(txAHistoryStr);
            } else {
                showNumber = showNumber + evt.getActionCommand();
                if (!showNumber.equals("0") && !showNumber.equals(""))
                {txAHistoryStr = txAHistoryStr + (evt.getActionCommand());}
                TxfLive.setText(txAHistoryStr);
            }
            TxfScreen.setText(showNumber);
        }
    }//GEN-LAST:event_numberClick

    private void jButtonCommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCommaActionPerformed
        // TODO add your handling code here:
        if (showNumber.indexOf(",") == -1 && !(txAHistoryStr.equals("") && !showNumber.equals(""))) {
            showNumber = showNumber + ",";
            if (showNumber.equals(",")) {
                showNumber = "0,";
            }
            TxfScreen.setText(showNumber);
            if (showNumber.equals("0,")) {
                
                    txAHistoryStr = txAHistoryStr + ("0,");
                
            } else {
                txAHistoryStr = txAHistoryStr + (evt.getActionCommand());
            }
            TxfLive.setText(txAHistoryStr);
            TxfScreen.setText(showNumber);
        }


    }//GEN-LAST:event_jButtonCommaActionPerformed

    private void jButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualsActionPerformed
        // TODO add your handling code here: 
        if ((!operation.equals(OperationType.NONE)) && !showNumber.isEmpty()) {
            showNumber = showNumber.replace(",", ".");
            operateTwo = Double.parseDouble(showNumber);
            txAHistoryStr = txAHistoryStr + (evt.getActionCommand());
            result = BasicOperations.makeOperation(operation, operateOne, operateTwo, decimalCounter);
            if (result % 1.0 == 0) {
                showNumber = Integer.toString(((int) (result)));
            } else {
                showNumber = Double.toString((result));
            }
            showNumber = showNumber.replace(".", ",");
            TxfScreen.setText(showNumber);
            txAHistoryStr = txAHistoryStr + (showNumber);
            TxfLive.setText(txAHistoryStr);
            //showNumber = "";
            TxAHistory.append(txAHistoryStr + "\n");
            txAHistoryStr = "";
            operation = OperationType.NONE;
            subOperation = OperationType.NONE;
            operateTwo = Double.MAX_VALUE;
        }
    }//GEN-LAST:event_jButtonEqualsActionPerformed

    private void jButtonClearEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearEndActionPerformed
        // TODO add your handling code here:
        if (!showNumber.equals("0") || !showNumber.equals("")) {
            int aux = showNumber.length();
            showNumber = "0";
            txAHistoryStr = txAHistoryStr.substring(0, (txAHistoryStr.length() - aux));
            TxfLive.setText(txAHistoryStr);
            TxfScreen.setText(showNumber);
        }

    }//GEN-LAST:event_jButtonClearEndActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        if (TxfLive.getText().substring((TxfLive.getText().length() - 1), TxfLive.getText().length()).equals("}")) {

            int first = TxfLive.getText().lastIndexOf("R");
            txAHistoryStr = txAHistoryStr.substring(0, first);
            TxfLive.setText(txAHistoryStr);
            TxfScreen.setText("0");
            showNumber = "0";
            subOperation = OperationType.NONE;
        } else if (!showNumber.equals("0")) {
            if (showNumber.length() == 1) {
                showNumber = "0";
                if (txAHistoryStr.length() == 1) {
                    txAHistoryStr = "";
                } else {
                    txAHistoryStr = txAHistoryStr.substring(0, (txAHistoryStr.length() - 1));
                }
                TxfLive.setText(txAHistoryStr);
                TxfScreen.setText(showNumber);


            } else {
                if (!operation.equals(OperationType.NONE)) {
                    showNumber = showNumber.substring(0, (showNumber.length() - 1));
                    txAHistoryStr = txAHistoryStr.substring(0, (txAHistoryStr.length() - 1));
                    TxfLive.setText(txAHistoryStr);
                    TxfScreen.setText(showNumber);
                }
            }
        }
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:

        showNumber = "0";
        txAHistoryStr = "";
        operation = OperationType.NONE;
        operateTwo = Double.MAX_VALUE;
        TxfLive.setText("");
        TxfScreen.setText("0");
        subOperation = OperationType.NONE;
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonCloseBracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseBracketActionPerformed
        // TODO add your handling code here:
        if ((!operation.equals(OperationType.NONE)) && !showNumber.equals("0")) {
            showNumber = showNumber.replace(",", ".");
            operateTwo = Double.parseDouble(showNumber);
            txAHistoryStr = txAHistoryStr + (evt.getActionCommand());
            result = BasicOperations.makeOperation(operation, operateOne, operateTwo, decimalCounter);
            operateOne = result;
            if (result % 1.0 == 0) {
                showNumber = Integer.toString(((int) (result)));
            } else {
                showNumber = Double.toString((result));
            }
            showNumber = showNumber.replace(".", ",");
            TxfScreen.setText(showNumber);
            TxfLive.setText(txAHistoryStr);
            subOperation = OperationType.NONE;
            operation = OperationType.BRACKETS;
        }
    }//GEN-LAST:event_jButtonCloseBracketActionPerformed

    private void jButtonOpenBracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenBracketActionPerformed
        // TODO add your handling code here:
        txAHistoryStr = txAHistoryStr + (evt.getActionCommand());
        TxfLive.setText(txAHistoryStr);
    }//GEN-LAST:event_jButtonOpenBracketActionPerformed

    private void jButtonClearHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearHistoryActionPerformed
        // TODO add your handling code here:
        TxAHistory.setText("");
    }//GEN-LAST:event_jButtonClearHistoryActionPerformed

    private void RequestOperation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestOperation
        // TODO add your handling code here:
        
        if (evt.getActionCommand().matches("-") && (showNumber.equals("") || showNumber.equals("0"))) {
            showNumber = "-";
            txAHistoryStr = txAHistoryStr + (evt.getActionCommand());
            TxfLive.setText(txAHistoryStr);
            TxfScreen.setText(showNumber);
        } else {
            subOperation = OperationType.NONE;
            showNumber = showNumber.replaceAll(",", ".");
            if ((operation.equals(OperationType.NONE)) && (subOperation.equals(OperationType.BRACKETS))) {

                operateTwo = Double.parseDouble(showNumber);
                txAHistoryStr = txAHistoryStr + (evt.getActionCommand());
                showNumber = "";
                result = BasicOperations.makeOperation(operation, operateOne, operateTwo, decimalCounter);
                if (result % 1.0 == 0) {
                    TxfScreen.setText(Integer.toString(((int) (result))));
                } else {
                    TxfScreen.setText(Double.toString((result)));
                }

                TxfLive.setText(txAHistoryStr);
                operateOne = result;
            } else {
                operateOne = Double.parseDouble(showNumber);
                if (txAHistoryStr.equals("")){txAHistoryStr=showNumber;}
                txAHistoryStr = txAHistoryStr + (evt.getActionCommand());
                showNumber = "";
                TxfLive.setText(txAHistoryStr);
                operateTwo = Double.MIN_VALUE;
            }
            switch (evt.getActionCommand()) {
                case "*":
                    operation = OperationType.MULTIPLY;
                    break;
                case "+":
                    operation = OperationType.ADD;
                    break;
                case "-":
                    operation = OperationType.LESS;
                    break;
                default:
                    operation = OperationType.NONE;
            }
        }
    }//GEN-LAST:event_RequestOperation

    private void jToggleLiveModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleLiveModeActionPerformed
        // TODO add your handling code here:
        if (jToggleLiveMode.getModel().isSelected()) {
            jButtonOpenBracket.setEnabled(true);
            jButtonCloseBracket.setEnabled(true);
        } else {
            jButtonOpenBracket.setEnabled(false);
            jButtonCloseBracket.setEnabled(false);
        }
    }//GEN-LAST:event_jToggleLiveModeActionPerformed

    private void reciproc(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reciproc
        // TODO add your handling code here:
        if (!showNumber.equals("0") && !showNumber.equals("")) {

            showNumber = showNumber.replaceAll(",", ".");
            result = Double.parseDouble(showNumber);
            jButtonBackActionPerformed(evt);
            txAHistoryStr = txAHistoryStr + ("Reciproc{" + result + "}");
            TxfLive.setText(txAHistoryStr);
            result = 1 / result;
            if (result % 1.0 == 0) {
                showNumber = Integer.toString(((int) (result)));
                TxfScreen.setText(showNumber);
            } else {
                showNumber = Double.toString((result));
                TxfScreen.setText(showNumber);
            }
            subOperation = OperationType.RECIPROC;
        }
    }//GEN-LAST:event_reciproc

    private void selectDecimalPrecision(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDecimalPrecision
        // TODO add your handling code here:
        decimalCounter = Integer.parseInt(evt.getActionCommand());
    }//GEN-LAST:event_selectDecimalPrecision

    private void showAboutDialog(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAboutDialog
        // TODO add your handling code here:
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_showAboutDialog

    private void jButtonChangeSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeSignActionPerformed
        // TODO add your handling code here:
        if (!showNumber.equals("0") && !showNumber.equals("")) {
            if (showNumber.charAt(0) == '-') {
                int aux = showNumber.length();
                txAHistoryStr = txAHistoryStr.substring(0, (txAHistoryStr.length() - aux));
                showNumber = showNumber.substring(1, showNumber.length());
                txAHistoryStr = txAHistoryStr + showNumber;
                TxfLive.setText(txAHistoryStr);
                TxfScreen.setText(showNumber);
            } else {
                int aux = showNumber.length();
                txAHistoryStr = txAHistoryStr.substring(0, (txAHistoryStr.length() - aux));
                showNumber = "-" + showNumber;
                txAHistoryStr = txAHistoryStr + showNumber;
                TxfLive.setText(txAHistoryStr);
                TxfScreen.setText(showNumber);
            }
        }
    }//GEN-LAST:event_jButtonChangeSignActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasicCalculator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxAHistory;
    private javax.swing.JTextField TxfLive;
    private javax.swing.JTextField TxfScreen;
    private javax.swing.JFrame aboutDialog;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonChangeSign;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonClearEnd;
    private javax.swing.JButton jButtonClearHistory;
    private javax.swing.JButton jButtonCloseBracket;
    private javax.swing.JButton jButtonComma;
    private javax.swing.JButton jButtonDivide;
    private javax.swing.JButton jButtonEight;
    private javax.swing.JButton jButtonEquals;
    private javax.swing.JButton jButtonFive;
    private javax.swing.JButton jButtonFour;
    private javax.swing.JButton jButtonLess;
    private javax.swing.JButton jButtonMultiply;
    private javax.swing.JButton jButtonNine;
    private javax.swing.JButton jButtonOne;
    private javax.swing.JButton jButtonOpenBracket;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonSeven;
    private javax.swing.JButton jButtonSix;
    private javax.swing.JButton jButtonTrhee;
    private javax.swing.JButton jButtonTwo;
    private javax.swing.JButton jButtonZero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonEightDecimals;
    private javax.swing.JRadioButtonMenuItem jRadioButtonFiveDecimals;
    private javax.swing.JRadioButtonMenuItem jRadioButtonFourDecimals;
    private javax.swing.JRadioButtonMenuItem jRadioButtonNoDecimals;
    private javax.swing.JRadioButtonMenuItem jRadioButtonOneDecimal;
    private javax.swing.JRadioButtonMenuItem jRadioButtonSevenDecimals;
    private javax.swing.JRadioButtonMenuItem jRadioButtonSixDecimals;
    private javax.swing.JRadioButtonMenuItem jRadioButtonThreeDecimals;
    private javax.swing.JRadioButtonMenuItem jRadioButtonTwoDecimals;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleLiveMode;
    private javax.swing.ButtonGroup precisionDecimalsGroup;
    // End of variables declaration//GEN-END:variables
}